name: Check for new SNMP Notifier releases
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron:  '0 0,4,8,12,16,20 * * *'

jobs:
  check:
    name: Detect new releases
    runs-on: ubuntu-latest
    outputs:
      release: ${{steps.check.outputs.release}}
    steps:
      - id: snmp-notifier-latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: maxwo/snmp_notifier
          excludes: prerelease, draft
      # Check out the tags of our repo to compare
      - name: Checkout canonical/snmp_notifier
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check
        name: Check for new releases
        run: |
          release=$(git show-ref --tags ${{steps.snmp-notifier-latest-release.outputs.release}} --quiet }} && echo -n '' || echo '${{ steps.snmp-notifier-latest-release.outputs.release }}' )
          if [ -n "${release}" ]; then
            echo "::set-output name=release::${release}"
            echo "New upstream release ${{steps.snmp-notifier-latest-release.outputs.release}} found"
          else
            echo "No new upstream release found"
          fi

  trigger-build:
    uses: ./.github/workflows/build-snmp-notifier-release.yaml
    needs: check
    if: ${{ needs.check.outputs.release != '' }}
    with:
      release: ${{needs.check.outputs.release}}
